### ISSUE TITLE
elasticsearch权限问题

### ISSUE THREAD

**Issue by kevinKaiF** [lionsoul2014/jcseg#36]
使用版本号：jcseg-2.0.1-RC2
es版本：2.4.1
异常信息：
Exception in thread "main" java.security.AccessControlException: access denied ("java.io.FilePermission" "plugins/jcseg/jcseg.properties" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:372)
	at java.security.AccessController.checkPermission(AccessController.java:559)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
	at java.io.File.exists(File.java:808)
	at org.lionsoul.jcseg.elasticsearch.index.analysis.JcsegIndicesAnalysis.<init>(JcsegIndicesAnalysis.java:39)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at <<<guice>>>
	at org.elasticsearch.node.Node.<init>(Node.java:213)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:194)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)

经过搜索，发现es有自己的权限策略，https://discuss.elastic.co/t/permission-denied-error-in-plugin-for-es-2-2-0/40915

**Comment by lionsoul2014** [comment]
一直有这个问题存在，参考下这个项目：https://gitee.com/lionsoul/elasticsearch-jcseg

追加一份新的security.policy，加上权限就OK了，然后再config/jvm.options中增加

```
-Djava.security.policy=security.policy
```

应用权限

**Comment by kevinKaiF** [comment]
好的，另外请教下，我想对luncene想深入学习，有没有什么可推荐的资料

**Comment by lionsoul2014** [comment]
2.4.1版本我不确定了，你看下config目录下是否有相关配置，没有更改elasticsearch启动文件增加相关配置也行。
lucene的深入个人建议如下：
1，lucene的使用熟练。
2，信息检索（倒排索引，BM25打分模型等）
3，其次是lucene的设计和实现哲学等。
