### ISSUE TITLE
接口不兼容

### ISSUE THREAD

**Issue by faywong** [lionsoul2014/jcseg#6]
```bash
/faywong/devel/elasticsearch-1.7.5/plugins/jcseg/jcseg-elasticsearch-1.9.9.jar!/es-plugin.properties]
org.elasticsearch.ElasticsearchException: Failed to load plugin class [org.lionsoul.jcseg.elasticsearch.plugin.analysis.jcseg.AnalysisJcsegPlugin]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:536)
	at org.elasticsearch.plugins.PluginsService.loadPluginsFromClasspath(PluginsService.java:411)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:116)
	at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:157)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:77)
	at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:245)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
Caused by: java.lang.IncompatibleClassChangeError: class org.lionsoul.jcseg.elasticsearch.plugin.analysis.jcseg.AnalysisJcsegPlugin has interface org.elasticsearch.plugins.Plugin as super class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:513)
```
运行环境：
elasticsearch-1.7.5
最新的Jcseg代码

**Comment by lionsoul2014** [comment]
lucene，elasticsearch升级很快，接口变化很频繁，很难做到每个版本都有支持！
默认的支持的最新的那个几个版本，elasticsearch-2.3.1：
1，升级下你的elasticsearch（2.x和1.x语法也不太兼容了）
2，jcseg-elasticsearch/pom.xml更改下，然后修改下里面的代码来兼容1.7.5

**Comment by lionsoul2014** [comment]
https://github.com/lionsoul2014/jcseg/tree/v1.9.7-release
这个tag下的支持是1.7.x的支持，可以融合下！

**Comment by faywong** [comment]
好的。非常感谢！
